### ISSUE TITLE
Update the API

### ISSUE THREAD

**Issue by Ricostyle21** [Vogeltak/magister6-api#9]
Could you update the API to the newest version?

**Comment by Vogeltak** [comment]
Dear @Ricostyle21Dev, as I am no longer a student with an institution making use of Magister, I do not have the means to develop an update myself. If you figure out a way to do it, please be my guest and submit a pull request.

**Comment by H3LL0U** [comment]
Hi,
I was scrolling through to see if anyone has made any simillar projects to the one I was working on and this one seems to be one of the only ones that used to work a long time ago. If anyone is interested in a package that lets you interact with magister you can visit here: [https://github.com/H3LL0U/MagisterPy] .
Thanks :)

**Comment by Vogeltak** [comment]
> Hi, I was scrolling through to see if anyone has made any simillar projects to the one I was working on and this one seems to be one of the only ones that used to work a long time ago. If anyone is interested in a package that lets you interact with magister you can visit here: https://github.com/H3LL0U/MagisterPy . Thanks :)

Glad to see the Magister APIs continue to be fun to poke at for the new generations as well! I've added a deprecation notice and linked to your repo in the README in d6ca4ab0346a144963dac9237c97c96d4ed93c3f.
